#!/usr/bin/env bash
set -euo pipefail

dnf -y install \
  "${AICAGE_PACKAGE_BASH_INSTALL:-bash}" \
  "${AICAGE_PACKAGE_BASH_COMPLETION_INSTALL:-bash-completion}" \
  "${AICAGE_PACKAGE_BATS_INSTALL:-bats}" \
  "${AICAGE_PACKAGE_BIND_UTILS_INSTALL:-bind-utils}" \
  "${AICAGE_PACKAGE_CA_CERTIFICATES_INSTALL:-ca-certificates}" \
  "${AICAGE_PACKAGE_CURL_INSTALL:-curl}" \
  "${AICAGE_PACKAGE_DNF_PLUGINS_CORE_INSTALL:-dnf-plugins-core}" \
  "${AICAGE_PACKAGE_FILE_INSTALL:-file}" \
  "${AICAGE_PACKAGE_GIT_INSTALL:-git}" \
  "${AICAGE_PACKAGE_GNUPG2_INSTALL:-gnupg2}" \
  "${AICAGE_PACKAGE_IMAGEMAGICK_INSTALL:-ImageMagick}" \
  "${AICAGE_PACKAGE_IPROUTE_INSTALL:-iproute}" \
  "${AICAGE_PACKAGE_JQ_INSTALL:-jq}" \
  "${AICAGE_PACKAGE_LESS_INSTALL:-less}" \
  "${AICAGE_PACKAGE_NANO_INSTALL:-nano}" \
  "${AICAGE_PACKAGE_NMAP_NCAT_INSTALL:-nmap-ncat}" \
  "${AICAGE_PACKAGE_OPENSSH_CLIENTS_INSTALL:-openssh-clients}" \
  "${AICAGE_PACKAGE_P7ZIP_INSTALL:-p7zip}" \
  "${AICAGE_PACKAGE_PATCH_INSTALL:-patch}" \
  "${AICAGE_PACKAGE_PROCPS_NG_INSTALL:-procps-ng}" \
  "${AICAGE_PACKAGE_RIPGREP_INSTALL:-ripgrep}" \
  "${AICAGE_PACKAGE_RSYNC_INSTALL:-rsync}" \
  "${AICAGE_PACKAGE_SHADOW_UTILS_INSTALL:-shadow-utils}" \
  "${AICAGE_PACKAGE_TAR_INSTALL:-tar}" \
  "${AICAGE_PACKAGE_TIME_INSTALL:-time}" \
  "${AICAGE_PACKAGE_TINI_INSTALL:-tini}" \
  "${AICAGE_PACKAGE_TREE_INSTALL:-tree}" \
  "${AICAGE_PACKAGE_TZDATA_INSTALL:-tzdata}" \
  "${AICAGE_PACKAGE_UNZIP_INSTALL:-unzip}" \
  "${AICAGE_PACKAGE_XZ_INSTALL:-xz}" \
  "${AICAGE_PACKAGE_YQ_INSTALL:-yq}" \
  "${AICAGE_PACKAGE_ZIP_INSTALL:-zip}"
