FORMATTERS_DISABLE_ERRORS: false



# prettier
JSON_PRETTIER_ARGUMENTS: "--tab-width 4"

# shfmt
BASH_SHFMT_ARGUMENTS: "--indent 2 -case-indent"

# trivy
REPOSITORY_TRIVY_ARGUMENTS: "--ignorefile ./.trivyignore.yaml"

# zizmor
ACTION_ZIZMOR_UNSECURED_ENV_VARIABLES:
  - GITHUB_TOKEN
